root = "."
tmp_dir = "tmp"

[build]
# 出力バイナリは .exe にする（tmp 配下に置くのが安全）
bin = "tmp/main.exe"

# テンプレは使わず、明示的に出力先とビルド対象を指定
# ルートが main パッケージなら '.' でOK。サブディレクトリなら ./cmd/app などに変更
cmd = "go build -o tmp/main.exe ."

# 監視対象の拡張子（必要に応じて追加）
include_ext = ["go"]

# 監視除外ディレクトリ（node_modules や client, tmp など）
exclude_dir = ["tmp", "client", "node_modules", ".git"]

# (任意) 変更からビルド開始までの遅延(ms)。頻繁に保存するなら少し待たせる
delay = 1000

# (任意) ビルドエラーが出たら実行を止める
stop_on_error = true
